# Generated by scripts/configure_compatibility.sh from .templates/ci.
# Edit templates under .templates/ci instead of editing generated target jobs.

name: Gitea CI/CD Workflow

env:
  PACKAGE_NAME: {{PACKAGE_NAME}}
  INTERNAL_PYPI_INDEX: {{INTERNAL_PYPI_INDEX}}
  UV_PYTHON_INSTALL_MIRROR: {{PYTHON_INSTALL_MIRROR}}

on:
  push:
    # 场景 1：Snapshot 模式
    # 每次推送到 main 分支，都会触发构建和发布 Dev 包
    branches:
      - "main"
    # 场景 2：Release 模式
    # 每次在 Gitea 网页上新建 Release (创建 Tag)，都会触发发布正式包
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  # ===========================================================================
  # 1. 构建与测试 (通用)
  # Gitea Actions 当前只支持简单 runs-on，因此异构 runner 由模板展开为静态 job。
  # ===========================================================================
{{COMPATIBILITY_JOBS}}

  build-and-test:
    name: Build and Test Gate
    runs-on: ubuntu-latest
    needs:
{{COMPATIBILITY_NEEDS}}
    steps:
      - name: Confirm compatibility jobs
        run: echo "All compatibility jobs passed."

{{DOCKER_CHECK_JOB}}
  publish:
    name: Publish to Gitea Registry
    needs: build-and-test
    runs-on: ubuntu-latest
    # 仅在 main 分支推送 或 打 Tag 时运行 (忽略 PR)
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: {{GITEA_CHECKOUT_ACTION}}
        with:
          fetch-depth: 0 # 发布阶段也需要完整历史来构建版本

      - name: Install uv
        run: |
          python3 -m ensurepip --upgrade || true
          python3 -m pip install --user --upgrade -i "${INTERNAL_PYPI_INDEX}" uv || \
            python3 -m pip install --user --upgrade --break-system-packages -i "${INTERNAL_PYPI_INDEX}" uv
          USER_BIN="$(python3 -m site --user-base)/bin"
          echo "$USER_BIN" >> "$GITHUB_PATH"
          export PATH="$USER_BIN:$PATH"
          uv --version

      - name: Build distributions
        run: uv build

      - name: Publish to Gitea Registry
        env:
          UV_PUBLISH_OWNER: ${{ secrets.OWNER }}
          UV_PUBLISH_PASSWORD: ${{ secrets.PASSWORD }}
          GITEA_HOST: "{{INTERNAL_GITEA_HOST}}"
        run: |
          PUBLISH_URL="${GITEA_HOST}/api/packages/${{ github.repository_owner }}/pypi"
          echo "🚀 Publishing to $PUBLISH_URL ..."
          uv publish --publish-url "$PUBLISH_URL" --username ${{ secrets.OWNER }} --password ${{ secrets.PASSWORD }}
