# Generated by scripts/configure_compatibility.sh from .templates/ci.
# Edit templates under .templates/ci instead of editing generated matrix entries.

name: Public Release from Gitea Mirror

env:
  UV_PYTHON_INSTALL_MIRROR: {{PYTHON_INSTALL_MIRROR}}
  PUBLIC_PYPI_INDEX: {{PUBLIC_PYPI_INDEX}}
  ACT_PYPI_INDEX: {{ACT_PYPI_INDEX}}
  UV_INDEX: {{PUBLIC_PYPI_INDEX}}
  UV_DEFAULT_INDEX: {{PUBLIC_PYPI_INDEX}}

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  get-metadata:
    runs-on: ubuntu-latest
    outputs:
      pkg_name: ${{ steps.package_name.outputs.value }}
    steps:
      - name: Checkout code (GitHub)
        if: ${{ env.ACT != 'true' }}
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          server="${GITHUB_SERVER_URL:-https://github.com}"
          repo="${GITHUB_REPOSITORY:?}"
          if [ -n "${GH_TOKEN:-}" ]; then
            remote="https://x-access-token:${GH_TOKEN}@${server#https://}/${repo}.git"
          else
            remote="${server}/${repo}.git"
          fi
          git init .
          git remote remove origin 2>/dev/null || true
          git remote add origin "$remote"
          git fetch --force --tags --prune origin "+refs/heads/*:refs/remotes/origin/*" "+refs/tags/*:refs/tags/*"
          git checkout --force "$GITHUB_SHA"

      - name: Extract package name
        id: package_name
        run: |
          NAME=$(grep -m 1 '^name =' pyproject.toml | cut -d '"' -f 2)
          echo "value=$NAME" >> $GITHUB_OUTPUT

  build-and-test:
    name: Test on ${{ matrix.platform }}/${{ matrix.arch }} (Py ${{ matrix.python-version }})
    runs-on: ${{ matrix.runner }}
    needs: get-metadata
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
{{COMPATIBILITY_MATRIX}}

    steps:
      - name: Checkout code (GitHub)
        if: ${{ env.ACT != 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          server="${GITHUB_SERVER_URL:-https://github.com}"
          repo="${GITHUB_REPOSITORY:?}"
          if [ -n "${GH_TOKEN:-}" ]; then
            remote="https://x-access-token:${GH_TOKEN}@${server#https://}/${repo}.git"
          else
            remote="${server}/${repo}.git"
          fi
          git init .
          git remote remove origin 2>/dev/null || true
          git remote add origin "$remote"
          git fetch --force --tags --prune origin "+refs/heads/*:refs/remotes/origin/*" "+refs/tags/*:refs/tags/*"
          git checkout --force "$GITHUB_SHA"

      - name: Install uv (GitHub)
        if: ${{ env.ACT != 'true' }}
        run: |
          if command -v python3 >/dev/null 2>&1; then
            PYTHON_BIN=python3
          else
            PYTHON_BIN=python
          fi
          "$PYTHON_BIN" -m pip install --user -i "${PUBLIC_PYPI_INDEX}" uv || \
            "$PYTHON_BIN" -m pip install --user --break-system-packages -i "${PUBLIC_PYPI_INDEX}" uv
          USER_BIN=$("$PYTHON_BIN" -c 'import os, site; print(os.path.join(site.USER_BASE, "Scripts" if os.name == "nt" else "bin"))')
          echo "$USER_BIN" >> "$GITHUB_PATH"
          "$USER_BIN/uv" --version

      - name: Install uv (act)
        if: ${{ env.ACT == 'true' }}
        shell: bash
        run: |
          python3 -m pip install --user -i "${ACT_PYPI_INDEX}" uv || \
            python3 -m pip install --user --break-system-packages -i "${ACT_PYPI_INDEX}" uv
          USER_BIN=$(python3 -c 'import os, site; print(os.path.join(site.USER_BASE, "Scripts" if os.name == "nt" else "bin"))')
          echo "$USER_BIN" >> "$GITHUB_PATH"
          "$USER_BIN/uv" --version

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies (GitHub)
        if: ${{ env.ACT != 'true' }}
        run: uv sync --python ${{ matrix.python-version }} --all-extras --dev --index "${{ env.PUBLIC_PYPI_INDEX }}" --default-index "${{ env.PUBLIC_PYPI_INDEX }}"

      - name: Install dependencies (act)
        if: ${{ env.ACT == 'true' }}
        env:
          UV_INDEX: {{ACT_PYPI_INDEX}}
          UV_DEFAULT_INDEX: {{ACT_PYPI_INDEX}}
        run: uv sync --python ${{ matrix.python-version }} --all-extras --dev --index "${{ env.ACT_PYPI_INDEX }}" --default-index "${{ env.ACT_PYPI_INDEX }}"

      - name: Lint and Format check
        run: |
          uv run --no-sync --python ${{ matrix.python-version }} ruff check .
          uv run --no-sync --python ${{ matrix.python-version }} ruff format --check .
          uv run --no-sync --python ${{ matrix.python-version }} mypy --package "${{ needs.get-metadata.outputs.pkg_name }}"

      - name: Run tests
        run: uv run --no-sync --python ${{ matrix.python-version }} pytest

      - name: Build documentation
        run: uv run --no-sync --python ${{ matrix.python-version }} mkdocs build --strict

{{DOCKER_CHECK_JOB}}
  deploy:
    name: Publish to Public PyPI
    runs-on: ubuntu-latest
    needs: [build-and-test, get-metadata]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    environment:
      name: pypi
      url: https://pypi.org/p/${{ needs.get-metadata.outputs.pkg_name }}

    permissions:
      id-token: write # 用于 PyPI Trusted Publishing
      contents: write # 💡 必须：用于将构建产物上传到 GitHub Release 页面

    steps:
      - name: Checkout code
        uses: {{GITHUB_CHECKOUT_ACTION}}
        with:
          fetch-depth: 0

      - name: Install uv
        uses: {{GITHUB_SETUP_UV_ACTION}}

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI
        run: uv publish

      - name: Upload artifacts to GitHub Release
        uses: {{GITHUB_RELEASE_ACTION}}
        with:
          files: dist/*
